import { describe, expect, it } from 'vitest';
import type { ArtifactDto, ProjectDto, RunDto, SessionDto, SessionLockDto, SessionSummaryDto, SettingsDto, SyncStatusBody, TabDto, TodoDto } from '@agent-hangar/shared';
import { defaultSessionView } from '../mediator/sessionView.ts';
import { initialState } from '../mediator/transition.ts';
import { applyEventsPage, applySubagents, eventsKey, initialStore, type Store } from '../store/store.ts';
import { absoluteTime, costLabel, percentLabel, relativeTime, shortModel, tokensLabel } from './format.ts';
import { presentHome } from './home.ts';
import { presentNewSession } from './newSession.ts';
import { presentArtifactCard, presentProject } from './project.ts';
import { presentProjects } from './projects.ts';
import { presentSessionRow } from './row.ts';
import { buildItems, presentSession } from './session.ts';
import { presentSessions } from './sessions.ts';
import { presentSettings } from './settings.ts';
import { presentShell } from './shell.ts';

const NOW = Date.parse('2026-09-02T12:00:00Z');
const project = (id: string, status: ProjectDto['status'] = 'active'): ProjectDto => ({ id, name: id, status, isScratch: false, path: `/w/${id}`, resolved: true, lastActivityAt: NOW - 3_600_000, runningCount: 0, openTodoCount: 0, memoHead: null, updatedAt: 1 });
const session = (id: string, over: Partial<SessionDto> = {}): SessionDto => ({ id, provider: 'claude-code', providerSessionId: 'u' + id, projectId: 'alpha', name: 'name-' + id, cwd: '/w/alpha', firstPrompt: 'first', aiTitle: null, startedAt: NOW - 7_200_000, lastActivityAt: NOW - 60_000, memo: null, hasTranscript: true, live: null, summary: { title: 't', oneLiner: 'one', body: 'b', state: 'done', nextSteps: [], source: 'baseline', sourceId: null, sourceModel: null, basedOnTurns: 2, updatedAt: 1 }, stats: { turns: 2, model: 'claude-fable-5-1', effort: 'high', filesChanged: 1, prUrl: null, inputTokens: 1234567, outputTokens: 10, contextPercent: null, costUsd: null }, fromScratch: false, lock: null, remoteOnly: false, ...over });
const runDto = (id: string, sessionId: string, endedAt: number | null = null): RunDto => ({ id, sessionId, deviceId: 'd', kind: 'start', tmuxName: `hangar-${id}`, pid: null, startedAt: NOW - 60_000, endedAt, endReason: endedAt ? 'exited' : null, heartbeatAt: 1 });
const tabDto = (id: string, runId: string, kind: 'agent' | 'shell', closedAt: number | null = null): TabDto => ({ id, runId, sessionId: 's1', kind, title: kind === 'agent' ? 'Claude' : `シェル ${id}`, tmuxName: `hangar-${runId}-${id}`, createdAt: 2, closedAt });
function storeWith(): Store {
  const s = initialStore();
  s.bootstrapped = true;
  s.projects = { alpha: project('alpha'), beta: project('beta', 'paused'), old: project('old', 'archived') };
  s.sessions = { s1: session('s1', { live: 'busy' }), s2: session('s2', { lastActivityAt: NOW - 86_400_000 * 3 }), s3: session('s3', { projectId: null }) };
  return s;
}

describe('format', () => {
  it('相対時刻', () => {
    expect(relativeTime(NOW - 30_000, NOW)).toBe('1 分未満前');
    expect(relativeTime(NOW - 3 * 60_000, NOW)).toBe('3 分前');
    expect(relativeTime(NOW - 2 * 3_600_000, NOW)).toBe('2 時間前');
    expect(relativeTime(NOW - 30 * 3_600_000, NOW)).toBe('昨日');
    expect(relativeTime(NOW - 5 * 86_400_000, NOW)).toBe('5 日前');
    const old = relativeTime(NOW - 40 * 86_400_000, NOW);
    expect(old).toBe(absoluteTime(NOW - 40 * 86_400_000).slice(0, 10));
    expect(old).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(relativeTime(null, NOW)).toBe('不明');
  });
  it('モデル名とトークン', () => {
    expect(shortModel('claude-fable-5-1')).toBe('fable 5.1');
    expect(shortModel('claude-haiku-4-5-20251001')).toBe('haiku 4.5');
    expect(shortModel(null)).toBe('');
    // 問いを閉じたときなどに Claude が書く形だけの返事は、モデルではない。
    expect(shortModel('<synthetic>')).toBe('');
    expect(tokensLabel(1234567)).toBe('1.2M');
    expect(tokensLabel(12345)).toBe('12k');
    expect(tokensLabel(999)).toBe('999');
  });
});

describe('presentShell', () => {
  it('現在のナビ項目とパンくずと索引の進行', () => {
    const state = { ...initialState(), screen: { name: 'project' as const, id: 'alpha' } };
    const store = storeWith();
    store.index = { phase: 'indexing', done: 10, total: 40 };
    const p = presentShell(state, store, NOW);
    expect(p.nav.find((n) => n.current)?.label).toBe('プロジェクト');
    expect(p.crumbs.map((c) => c.label)).toEqual(['プロジェクト', 'alpha']);
    expect(p.indexLabel).toBe('索引 10 / 40 件');
  });
});

describe('ローカルコマンドの記録', () => {
  const sys = (seq: number, text: string) => ({ kind: 'system' as const, seq, ts: 1, text });
  const events = [
    sys(1, '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'),
    sys(2, '<command-name>/exit</command-name>\n            <command-message>exit</command-message>\n            <command-args></command-args>'),
    sys(3, '<local-command-stdout>(no content)</local-command-stdout>'),
    sys(4, '<command-name>/model</command-name><command-message>model</command-message><command-args>opus</command-args>'),
    sys(5, '<local-command-stdout>Set model to opus</local-command-stdout>'),
  ];
  it('決まり文句と空の出力は落とし、コマンドは 1 行に、出力は中身だけにする', () => {
    expect(buildItems(events, { showThinking: false, showRaw: false, subagents: [] }).map((i) => 'text' in i ? i.text : '')).toEqual(['/exit', '/model opus', 'Set model to opus']);
  });
  it('生の記録を出すときはそのまま出す', () => {
    expect(buildItems(events, { showThinking: false, showRaw: true, subagents: [] }).filter((i) => i.kind === 'system')).toHaveLength(5);
  });
});

describe('presentHome', () => {
  // 入力待ちが 2 件（w1 は 12 分、w2 は 3 分）、作業中が 1 件（s1）、休みが 1 件（i1）。
  const homeStore = () => {
    const s = storeWith();
    s.sessions = {
      ...s.sessions,
      w1: session('w1', { live: 'waiting', lastActivityAt: NOW - 12 * 60_000, activity: { tool: 'AskUserQuestion', summary: 'AskUserQuestion', question: 'どちらにしますか？' } }),
      w2: session('w2', { live: 'waiting', lastActivityAt: NOW - 3 * 60_000, activity: null }),
      i1: session('i1', { live: 'idle', lastActivityAt: NOW - 8 * 60_000, stats: { ...session('i1').stats, contextPercent: 22 } }),
    };
    s.sessions.s1 = { ...s.sessions.s1!, activity: { tool: 'Edit', summary: 'packages/ui/src/keys.ts', question: null }, stats: { ...s.sessions.s1!.stats, contextPercent: 38.4 } };
    return s;
  };
  it('確かめるは全プロジェクトの候補を古い順に並べ、完了と矛盾した行は数えない', () => {
    const store = homeStore();
    store.projects = { ...store.projects, beta: { ...project('beta'), name: 'beta' } };
    store.todos = {
      a: todoDto('a', 1, false, { sessionId: 's1', note: '新しい', at: NOW - 60_000 }, 'alpha'),
      b: todoDto('b', 1, false, { sessionId: null, note: null, at: NOW - 30 * 60_000 }, 'beta'),
      // done かつ candidate は DTO では起きない（サーバが null にする）が、古いサーバや手で作った値でも数えない。
      c: todoDto('c', 2, true, { sessionId: 's1', note: 'x', at: NOW - 90 * 60_000 }, 'alpha'),
      d: todoDto('d', 3, false, null, 'alpha'),
    };
    const h = presentHome(initialState(), store, NOW);
    expect(h.confirm).toEqual([
      { id: 'b', text: 'やる b', projectId: 'beta', projectName: 'beta', sessionName: '不明なセッション', ago: '30 分前', note: '根拠は書かれていません' },
      { id: 'a', text: 'やる a', projectId: 'alpha', projectName: 'alpha', sessionName: 'name-s1', ago: '1 分前', note: '新しい' },
    ]);
    expect(h.projects.find((p) => p.id === 'alpha')!.counts).toContain('確かめる 1');
  });
  it('候補が無ければ確かめるは空で、件数にも出さない', () => {
    const h = presentHome(initialState(), homeStore(), NOW);
    expect(h.confirm).toEqual([]);
    expect(h.projects.every((p) => !p.counts.includes('確かめる'))).toBe(true);
  });
  it('要対応は入力待ちを長く待っている順に拾い、問いが無ければ決まりの文を出す', () => {
    // w1 は hangar の run で動いている。w2 は別のターミナル（iTerm など）で動いていて、hangar の run が無い。
    const store = homeStore();
    store.runs = { rw1: runDto('rw1', 'w1') };
    expect(presentHome(initialState(), store, NOW).attention).toEqual([
      { id: 'w1', name: 'name-w1', projectName: 'alpha', waited: '12 分', question: 'どちらにしますか？', answer: 'terminal' },
      { id: 'w2', name: 'name-w2', projectName: 'alpha', waited: '3 分', question: '入力を待っています', answer: null },
    ]);
  });
  it('外のターミナルで動く入力待ちは引き取りを、バックグラウンドのものは attach を出す', () => {
    const store = homeStore();
    const live = (sessionId: string, over = {}) => ({ sessionId, status: 'waiting' as const, name: null, nameSource: null, cwd: '/w/alpha', pid: 1, entrypoint: 'cli', ...over });
    store.live = [live('uw1'), live('uw2', { background: { jobId: 'abcd1234' } })];
    const a = presentHome(initialState(), store, NOW).attention;
    expect(a.find((c) => c.id === 'w1')!.answer).toBe('adopt');
    expect(a.find((c) => c.id === 'w2')!.answer).toBe('attach');
    // hangar の run があれば、その端末で答える。
    store.runs = { rw1: runDto('rw1', 'w1') };
    expect(presentHome(initialState(), store, NOW).attention.find((c) => c.id === 'w1')!.answer).toBe('terminal');
  });
  it('終わった run しか無い入力待ちは、hangar の端末で答えられない', () => {
    const store = homeStore();
    store.runs = { rw1: runDto('rw1', 'w1', NOW - 1_000) };
    expect(presentHome(initialState(), store, NOW).attention.find((a) => a.id === 'w1')!.answer).toBeNull();
  });
  it('答えた後の AskUserQuestion のように、対象がツール名と同じなら対象を空にする', () => {
    const store = homeStore();
    store.sessions.s1 = { ...store.sessions.s1!, activity: { tool: 'AskUserQuestion', summary: 'AskUserQuestion', question: null } };
    expect(presentHome(initialState(), store, NOW).running[0]!.activity).toEqual({ tool: 'AskUserQuestion', summary: '' });
  });
  it('対象の先頭がツール名と半角空白なら、その繰り返しを削る', () => {
    const store = homeStore();
    store.sessions.s1 = { ...store.sessions.s1!, activity: { tool: 'Bash', summary: 'Bash npx vitest run sync', question: null } };
    expect(presentHome(initialState(), store, NOW).running[0]!.activity).toEqual({ tool: 'Bash', summary: 'npx vitest run sync' });
  });
  it('対象がツール名で始まっていても、続きが半角空白でなければそのまま出す', () => {
    const store = homeStore();
    store.sessions.s1 = { ...store.sessions.s1!, activity: { tool: 'Read', summary: 'Readme.md', question: null } };
    expect(presentHome(initialState(), store, NOW).running[0]!.activity).toEqual({ tool: 'Read', summary: 'Readme.md' });
  });
  it('実行中は作業中と休みを拾い、入力待ちは要対応だけに出す', () => {
    const p = presentHome(initialState(), homeStore(), NOW);
    expect(p.running.map((r) => r.id)).toEqual(['s1', 'i1']);
    expect(p.running[0]).toEqual({ id: 's1', name: 'name-s1', live: 'busy', elapsed: '2 時間', meta: 'alpha · fable 5.1 · high', activity: { tool: 'Edit', summary: 'packages/ui/src/keys.ts' }, note: null, contextPercent: 38.4, contextLabel: '38%' });
    expect(p.running[1]).toMatchObject({ live: 'idle', activity: null, note: '休み。最後の返答から 8 分', contextPercent: 22, contextLabel: '22%' });
  });
  it('作業中でも呼び出しがまだ無ければ「作業中」、レジストリに載る前の run は「起動しています」', () => {
    // 信頼確認のダイアログ待ちの run は Claude のレジストリにまだ載らない。
    const store = storeWith();
    store.runs = { r2: runDto('r2', 's2'), r3: runDto('r3', 's3', NOW) };
    const p = presentHome(initialState(), store, NOW);
    expect(p.running.map((r) => r.id)).toEqual(['s1', 's2']);
    expect(p.running[0]).toMatchObject({ activity: null, note: '作業中', contextLabel: '未取得' });
    expect(p.running[1]).toMatchObject({ live: null, activity: null, note: '起動しています' });
  });
  it('最近は要対応と実行中に出したものを除き、新しい順に並べる', () => {
    expect(presentHome(initialState(), homeStore(), NOW).recent.map((r) => r.id)).toEqual(['s3', 's2']);
  });
  it('終わったセッションは札から消えて、最近に入る', () => {
    const store = homeStore();
    store.sessions.s1 = { ...store.sessions.s1!, live: null, lastActivityAt: NOW - 30_000 };
    const p = presentHome(initialState(), store, NOW);
    expect(p.running.map((r) => r.id)).toEqual(['i1']);
    expect(p.recent[0]!.id).toBe('s1');
  });
  it('プロジェクトは active だけを小さな一覧にし、0 の数は出さない', () => {
    const store = homeStore();
    // サーバの runningCount は入力待ちも含む。入力待ちは要対応に数えるので、実行中からは引く。
    store.projects.alpha = { ...store.projects.alpha!, runningCount: 4, openTodoCount: 3 };
    expect(presentHome(initialState(), store, NOW).projects).toEqual([{ id: 'alpha', name: 'alpha', status: 'active', counts: '実行中 2 · TODO 3 · 要対応 2' }]);
    store.projects.alpha = { ...store.projects.alpha!, runningCount: 2 };
    expect(presentHome(initialState(), store, NOW).projects[0]!.counts).toBe('TODO 3 · 要対応 2');
    store.projects.alpha = { ...store.projects.alpha!, runningCount: 0, openTodoCount: 0 };
    store.sessions = { s2: store.sessions.s2! };
    expect(presentHome(initialState(), store, NOW).projects[0]!.counts).toBe('');
  });
});

describe('presentProjects', () => {
  it('セクション分けと絞り込みとアーカイブ', () => {
    const p = presentProjects(initialState(), storeWith(), NOW, '', false);
    expect(p.sections.map((s) => [s.status, s.cards.length])).toEqual([['active', 1], ['paused', 1], ['done', 0]]);
    expect(p.archivedCount).toBe(1);
    expect(presentProjects(initialState(), storeWith(), NOW, 'bet', false).sections[1]!.cards).toHaveLength(1);
    expect(presentProjects(initialState(), storeWith(), NOW, 'bet', false).sections[0]!.cards).toHaveLength(0);
    expect(presentProjects(initialState(), storeWith(), NOW, '', true).sections.map((s) => s.status)).toEqual(['active', 'paused', 'done', 'archived']);
  });
});

describe('presentProject', () => {
  it('実行中を先頭に、その後を新しい順に', () => {
    const store = storeWith();
    store.sessions.s4 = session('s4', { live: 'idle', lastActivityAt: NOW - 86_400_000 * 9 });
    const p = presentProject(initialState(), store, NOW, 'alpha');
    expect(p.sessions.map((s) => s.id)).toEqual(['s1', 's4', 's2']);
    expect(presentProject(initialState(), store, NOW, 'nope').notFound).toBe(true);
  });
});

describe('presentSession', () => {
  it('ツール結果を呼び出しに畳み込み、思考は既定で隠し、サブエージェントを対応づける', () => {
    let store = storeWith();
    store = applyEventsPage(store, eventsKey('s1', null), { sessionId: 's1', total: 6, nextSeq: null, events: [
      { kind: 'user', seq: 0, ts: NOW, text: 'hi' },
      { kind: 'thinking', seq: 1, text: 'think' },
      { kind: 'tool_call', seq: 2, toolId: 't1', name: 'Agent', input: { description: 'x' }, summary: 'Agent x' },
      { kind: 'tool_result', seq: 3, toolId: 't1', text: 'done', isError: false },
      { kind: 'meta', seq: 4, name: 'ai-title', value: {} },
      { kind: 'assistant', seq: 5, text: 'bye' },
    ] }, false);
    store = applySubagents(store, 's1', ['abc']);
    const p = presentSession(initialState(), store, NOW, 's1');
    expect(p.items.map((i) => i.kind)).toEqual(['user', 'tool', 'assistant']);
    expect(p.items[1]).toMatchObject({ kind: 'tool', summary: 'Agent x', result: { text: 'done', isError: false }, subagent: { agentId: 'abc', label: 'Agent x' } });
    expect(p).toMatchObject({ name: 'name-s1', live: 'busy', tokens: '1.2M', turns: 2, loaded: 6, total: 6, hasMore: false, projectName: 'alpha' });
    expect(p.summary).toMatchObject({ title: 't', sourceLabel: '自動', stateLabel: '完了' });
    const state = { ...initialState(), sessionView: { s1: { ...defaultSessionView(), showThinking: true, showRaw: true, summaryOpen: true } } };
    const q = presentSession(state, store, NOW, 's1');
    expect(q.items.map((i) => i.kind)).toEqual(['user', 'thinking', 'tool', 'meta', 'assistant']);
    expect(q.summaryOpen).toBe(true);
  });
  it('実行中なら状態と経過の札を作り、変更数を渡す', () => {
    const store = storeWith();
    expect(presentSession(initialState(), store, NOW, 's1')).toMatchObject({ liveLabel: '作業中 2 時間', filesChanged: 1 });
    expect(presentSession(initialState(), store, NOW, 's2').liveLabel).toBeNull();
  });
  // Home の要対応と休みの札は最後の動きから数える。同じセッションで待ちの長さが 2 つに割れないよう揃える。
  it('入力待ちと休みは最後の動きから、作業中は始まりから数える', () => {
    const store = storeWith();
    store.sessions.s1 = { ...store.sessions.s1!, live: 'waiting' };
    expect(presentSession(initialState(), store, NOW, 's1').liveLabel).toBe('入力待ち 1 分');
    store.sessions.s1 = { ...store.sessions.s1!, live: 'idle' };
    expect(presentSession(initialState(), store, NOW, 's1').liveLabel).toBe('休み 1 分');
  });
  it('遡って足したページも seq の順に並べ、残りは総数と持っている数で決める', () => {
    let store = storeWith();
    const k = eventsKey('s1', null);
    // 画面を開いたときは最新の側のページが入る。
    store = applyEventsPage(store, k, { sessionId: 's1', total: 4, nextSeq: null, events: [
      { kind: 'user', seq: 2, ts: NOW, text: 'newer' },
      { kind: 'assistant', seq: 3, text: 'newest' },
    ] }, false);
    expect(presentSession(initialState(), store, NOW, 's1')).toMatchObject({ hasMore: true, loaded: 2, total: 4 });
    // 遡ったページは後ろに足されるが、表示は seq の順に戻す。
    store = applyEventsPage(store, k, { sessionId: 's1', total: 4, nextSeq: null, events: [
      { kind: 'user', seq: 0, ts: NOW, text: 'oldest' },
      { kind: 'assistant', seq: 1, text: 'older' },
    ] }, true);
    const p = presentSession(initialState(), store, NOW, 's1');
    expect(p.items.map((i) => i.seq)).toEqual([0, 1, 2, 3]);
    expect(p.items.map((i) => ('text' in i ? i.text : ''))).toEqual(['oldest', 'older', 'newer', 'newest']);
    expect(p).toMatchObject({ hasMore: false, loaded: 4 });
  });
  it('要約の詳細に出す要約器とモデルと生成の時刻を作る', () => {
    const store = storeWith();
    const at = NOW - 3_600_000;
    const sum = (over: Partial<SessionSummaryDto>): SessionSummaryDto => ({ title: 't', oneLiner: 'one', body: 'b', state: 'done', nextSteps: [], source: 'post_hoc', sourceId: null, sourceModel: null, basedOnTurns: 5, updatedAt: at, ...over });
    store.sessions.s1 = session('s1', { summary: sum({ sourceId: 'lmstudio', sourceModel: 'gemma-4-26b-a4b-it-heretic' }) });
    expect(presentSession(initialState(), store, NOW, 's1').summary).toMatchObject({ sourceLabel: '事後', summarizerLabel: 'lmstudio / gemma-4-26b-a4b-it-heretic', generatedAt: absoluteTime(at) });
    // 種類は source_id が決める。モデル名から推測しない。
    store.sessions.s1 = session('s1', { summary: sum({ sourceId: 'claude-headless', sourceModel: 'haiku' }) });
    expect(presentSession(initialState(), store, NOW, 's1').summary).toMatchObject({ summarizerLabel: 'claude / haiku' });
    // claude を名に含むモデルを LM Studio で使っても、lmstudio のままである。
    store.sessions.s1 = session('s1', { summary: sum({ sourceId: 'lmstudio', sourceModel: 'claude-ish-7b' }) });
    expect(presentSession(initialState(), store, NOW, 's1').summary).toMatchObject({ summarizerLabel: 'lmstudio / claude-ish-7b' });
    // モデル名を言えなかったときは種類だけを出す。
    store.sessions.s1 = session('s1', { summary: sum({ sourceId: 'lmstudio', sourceModel: null }) });
    expect(presentSession(initialState(), store, NOW, 's1').summary).toMatchObject({ summarizerLabel: 'lmstudio' });
    // source_id を持たない古い行は、種類が分からないので不明と出す。
    store.sessions.s1 = session('s1', { summary: sum({ sourceId: null, sourceModel: 'gemma-4-26b-a4b-it-heretic' }) });
    expect(presentSession(initialState(), store, NOW, 's1').summary).toMatchObject({ summarizerLabel: '不明 / gemma-4-26b-a4b-it-heretic' });
    // 土台の要約は要約器を通していないので、種類もモデルも無い。
    store.sessions.s1 = session('s1');
    expect(presentSession(initialState(), store, NOW, 's1').summary).toMatchObject({ summarizerLabel: null, generatedAt: absoluteTime(1) });
  });
  it('無いセッションは notFound。run だけ先に届いていれば読み込み中', () => {
    expect(presentSession(initialState(), storeWith(), NOW, 'zz')).toMatchObject({ notFound: true, loadingSession: false });
    const store = storeWith();
    store.runs = { r9: runDto('r9', 'zz') };
    expect(presentSession(initialState(), store, NOW, 'zz')).toMatchObject({ notFound: false, loadingSession: true });
  });
});

describe('presentSessions', () => {
  it('検索語が無ければ全件、あれば結果だけを抜粋付きで', () => {
    let store = storeWith();
    const all = presentSessions(initialState(), store, NOW);
    expect(all.mode).toBe('all');
    expect(all.rows).toHaveLength(3);
    expect(all.projects.map((p) => p.name)).toEqual(['alpha', 'beta', 'old']);
    store = { ...store, search: { params: { q: 'hi' }, result: { hits: [{ sessionId: 's2', matchCount: 2, snippets: [{ seq: 1, role: 'user', text: '…hi…' }] }], total: 1 }, loading: false } };
    const state = { ...initialState(), screen: { name: 'sessions' as const, q: 'hi' }, search: { text: 'hi', filter: {} } };
    const r = presentSessions(state, store, NOW);
    expect(r.mode).toBe('search');
    expect(r.rows.map((x) => x.id)).toEqual(['s2']);
    expect(r.rows[0]!.excerpt).toEqual([{ text: '…', hit: false }, { text: 'hi', hit: true }, { text: '…', hit: false }]);
  });
});

describe('presentSession（実行中）', () => {
  it('run とタブと選択、信頼ダイアログの案内、再開の可否', () => {
    const store = storeWith();
    store.runs = { r1: runDto('r1', 's1') };
    store.tabs = { r1: tabDto('r1', 'r1', 'agent'), t1: tabDto('t1', 'r1', 'shell'), t0: tabDto('t0', 'r1', 'shell', 9) };
    const p = presentSession(initialState(), store, NOW, 's1');
    expect(p.run).toEqual({ id: 'r1', kind: 'start', alive: true, started: '1 分前' });
    expect(p.tabs).toEqual([{ id: 'r1', title: 'Claude', kind: 'agent', selected: true, closable: false }, { id: 't1', title: 'シェル t1', kind: 'shell', selected: false, closable: true }]);
    expect(p.selectedTab).toBe('r1');
    expect(p).toMatchObject({ trustHint: false, canResume: false, canFork: false, transcriptOpen: true });
    const state = { ...initialState(), sessionView: { s1: { ...defaultSessionView(), selectedTab: 't1', transcriptOpen: false } } };
    const q = presentSession(state, store, NOW, 's1');
    expect(q.selectedTab).toBe('t1');
    expect(q.tabs[1]!.selected).toBe(true);
    expect(q.transcriptOpen).toBe(false);
    store.sessions.s1 = { ...store.sessions.s1!, live: null };
    expect(presentSession(initialState(), store, NOW, 's1').trustHint).toBe(true);
  });
  it('選んでいたタブが閉じたら Claude タブに戻る', () => {
    const store = storeWith();
    store.runs = { r1: runDto('r1', 's1') };
    store.tabs = { r1: tabDto('r1', 'r1', 'agent'), t1: tabDto('t1', 'r1', 'shell', 9) };
    const state = { ...initialState(), sessionView: { s1: { ...defaultSessionView(), selectedTab: 't1' } } };
    const p = presentSession(state, store, NOW, 's1');
    expect(p.selectedTab).toBe('r1');
    expect(p.tabs).toEqual([{ id: 'r1', title: 'Claude', kind: 'agent', selected: true, closable: false }]);
  });
  it('run が無ければ再開できる。送信中は不可', () => {
    const store = storeWith();
    store.sessions.s2 = { ...store.sessions.s2!, live: null };
    expect(presentSession(initialState(), store, NOW, 's2')).toMatchObject({ run: null, tabs: [], selectedTab: null, canResume: true, canFork: true, trustHint: false });
    expect(presentSession({ ...initialState(), launch: { kind: 'submitting' } }, store, NOW, 's2').canResume).toBe(false);
    store.sessions.s2 = { ...store.sessions.s2!, hasTranscript: false };
    expect(presentSession(initialState(), store, NOW, 's2').canResume).toBe(false);
  });
  it('終了した run でもシェルタブが残っていれば run を出し、Claude タブは alive でない', () => {
    const store = storeWith();
    store.sessions.s2 = { ...store.sessions.s2!, live: null };
    store.runs = { r1: runDto('r1', 's2', NOW) };
    store.tabs = { r1: { ...tabDto('r1', 'r1', 'agent'), sessionId: 's2' }, t1: { ...tabDto('t1', 'r1', 'shell'), sessionId: 's2' } };
    const p = presentSession(initialState(), store, NOW, 's2');
    expect(p.run).toMatchObject({ id: 'r1', alive: false });
    expect(p.canResume).toBe(true);
    expect(p.tabs.map((t) => t.id)).toEqual(['r1', 't1']);
  });
});

describe('presentNewSession', () => {
  it('オーバーレイが newSession のときだけ、解決済みでアーカイブでないプロジェクトを出す', () => {
    const store = storeWith();
    store.projects.gone = { ...project('gone'), resolved: false };
    expect(presentNewSession(initialState(), store)).toBeNull();
    const state = { ...initialState(), overlay: { kind: 'newSession' as const, projectId: 'beta', scratch: false }, launch: { kind: 'failed' as const, message: 'x' } };
    const p = presentNewSession(state, store)!;
    expect(p.projects.map((x) => x.id)).toEqual(['alpha', 'beta']);
    expect(p).toMatchObject({ projectId: 'beta', submitting: false, error: 'x' });
    expect(presentNewSession({ ...state, launch: { kind: 'submitting' } }, store)!.submitting).toBe(true);
  });
});

describe('presentSettings（フェーズ 2）', () => {
  it('ツールのパスと MCP のコマンド', () => {
    const store = storeWith();
    store.settings = { workspaceRoot: '/w', claudeDir: '/c', tmuxPath: '/opt/homebrew/bin/tmux', terminalApp: 'iterm', codePath: null, lmStudioUrl: 'http://127.0.0.1:1234', lmStudioModel: null, summaryFallback: true, summaryHourlyCap: 20, allowExternalSummarizer: false, syncClaudeConfig: false, nodePath: null, claudePath: null };
    expect(presentSettings(initialState(), store)).toMatchObject({ tmuxPath: '/opt/homebrew/bin/tmux', terminalApp: 'iterm', codePath: null, mcpInstallCommand: 'npm run hangar -- mcp install' });
    store.settings = null;
    expect(presentSettings(initialState(), store)).toMatchObject({ tmuxPath: null, terminalApp: 'terminal', codePath: null });
  });
});

const todoDto = (id: string, position: number, done = false, candidate: TodoDto['candidate'] = null, projectId = 'p1'): TodoDto => ({ id, projectId, text: `やる ${id}`, done, position, sessionId: null, updatedAt: 1, candidate });
const artDto = (id: string, over: Partial<ArtifactDto> = {}): ArtifactDto => ({ id, projectId: 'p1', url: `https://claude.ai/code/artifact/${id}`, title: `題名 ${id}`, description: '説明', favicon: '📊', filePath: null, fileExists: false, firstPublishedAt: NOW - 100_000, lastPublishedAt: NOW - 60_000, versionCount: 2, sessionIds: ['s1'], ...over });
const scratchProject = (): ProjectDto => ({ ...project('sc'), name: 'スクラッチ', isScratch: true, path: '/h/.agent-hangar/scratch', lastActivityAt: NOW });

describe('書式', () => {
  it('percentLabel と costLabel', () => {
    expect(percentLabel(null)).toBe('未取得');
    expect(percentLabel(47.4)).toBe('47%');
    expect(percentLabel(0)).toBe('0%');
    expect(costLabel(null)).toBe('');
    expect(costLabel(1.234)).toBe('$1.23');
  });
});

describe('presentShell の接続', () => {
  it('つながっている間は何も出さない', () => {
    const s = { ...initialState(), connection: 'connected' as const };
    expect(presentShell(s, initialStore(), NOW).conn).toEqual({ visible: false, staleLabel: '', retryLabel: '' });
  });
  it('切れている間は、止まった時刻と次に試すまでの秒を出す', () => {
    const s = { ...initialState(), connection: 'disconnected' as const, staleSince: NOW - 120_000, nextRetryAt: NOW + 7_500 };
    expect(presentShell(s, initialStore(), NOW).conn).toEqual({ visible: true, staleLabel: '画面は 2 分前のまま止まっています', retryLabel: '8 秒後に再接続します' });
  });
  it('切れた直後は、時刻を言わずに止まったとだけ言う', () => {
    const s = { ...initialState(), connection: 'disconnected' as const, staleSince: NOW - 30_000, nextRetryAt: NOW + 2_000 };
    expect(presentShell(s, initialStore(), NOW).conn.staleLabel).toBe('画面の更新が止まっています');
  });
  it('待ち時間が尽きたら、試している最中だと出す', () => {
    const s = { ...initialState(), connection: 'disconnected' as const, staleSince: NOW, nextRetryAt: NOW };
    expect(presentShell(s, initialStore(), NOW).conn.retryLabel).toBe('再接続しています');
  });
  it('最初の接続の間はヘッダーに出さない。読み込み中の画面が担うからである', () => {
    expect(presentShell(initialState(), initialStore(), NOW).conn.visible).toBe(false);
  });
});

describe('presentShell の使用量', () => {
  it('値が無ければ null、あれば百分率と最終更新', () => {
    const empty = presentShell(initialState(), initialStore(), NOW);
    expect(empty.usage).toEqual({ fiveHour: null, sevenDay: null, updatedLabel: null });
    const store = { ...initialStore(), usage: { fiveHour: { usedPercent: 47, resetsAt: null }, sevenDay: { usedPercent: 7, resetsAt: null }, updatedAt: NOW - 600_000 } };
    expect(presentShell(initialState(), store, NOW).usage).toEqual({ fiveHour: 47, sevenDay: 7, updatedLabel: '10 分前' });
  });
});

describe('presentProject の右レール', () => {
  it('TODO とメモとアーティファクトを並べ、スクラッチは印を付ける', () => {
    const store: Store = {
      ...initialStore(),
      projects: { p1: { ...project('p1'), name: 'alpha', path: '/w/alpha', lastActivityAt: NOW, openTodoCount: 1, memoHead: '# alpha' } },
      todos: { t2: todoDto('t2', 2, true), t1: todoDto('t1', 1) },
      memos: { p1: { projectId: 'p1', markdown: '# alpha\n本文', updatedAt: 5 } },
      artifacts: { a1: artDto('a1'), a2: artDto('a2', { projectId: 'p2' }) },
    };
    const p = presentProject(initialState(), store, NOW, 'p1');
    expect(p.todos).toEqual([{ id: 't1', text: 'やる t1', done: false, candidate: null }, { id: 't2', text: 'やる t2', done: true, candidate: null }]);
    expect(p.memo).toEqual({ markdown: '# alpha\n本文', updatedAt: 5 });
    expect(p.artifacts.map((a) => a.id)).toEqual(['a1']);
    expect(p.isScratch).toBe(false);
  });
  it('候補の TODO は根拠とセッションと経過を出し、分からないものは決まりの文にする', () => {
    const store = storeWith();
    store.projects = { p1: { ...project('p1'), name: 'alpha' } };
    store.sessions = { s1: session('s1', { name: '起動画面の作り直し', projectId: 'p1' }) };
    store.todos = {
      t1: todoDto('t1', 1, false, { sessionId: 's1', note: '直して確かめた', at: NOW - 12 * 60_000 }),
      t2: todoDto('t2', 2, false, { sessionId: 'gone', note: null, at: NOW - 60 * 60_000 }),
      t3: todoDto('t3', 3, false, { sessionId: null, note: 'n', at: NOW - 5 * 60_000 }),
      t4: todoDto('t4', 4),
    };
    const p = presentProject(initialState(), store, NOW, 'p1');
    expect(p.todos.map((t) => t.candidate)).toEqual([
      { note: '直して確かめた', sessionId: 's1', sessionName: '起動画面の作り直し', ago: '12 分前' },
      { note: '根拠は書かれていません', sessionId: null, sessionName: '不明なセッション', ago: '1 時間前' },
      { note: 'n', sessionId: null, sessionName: '不明なセッション', ago: '5 分前' },
      null,
    ]);
  });
  it('アーティファクトのカードは題名と最終公開と編集の可否を持つ', () => {
    expect(presentArtifactCard(artDto('a1'), NOW)).toEqual({ id: 'a1', title: '題名 a1', description: '説明', favicon: '📊', url: 'https://claude.ai/code/artifact/a1', lastPublished: '1 分前', versionCount: 2, canOpenEditor: false });
    const manual = presentArtifactCard(artDto('a2', { title: null, favicon: null, description: null, filePath: '/w/alpha/x.html', fileExists: true }), NOW);
    expect(manual).toMatchObject({ title: 'a2', favicon: '📄', canOpenEditor: true });
  });
});

describe('presentProjects と presentHome（スクラッチ）', () => {
  it('スクラッチのプロジェクトはカードに出さない', () => {
    const store: Store = { ...initialStore(), projects: { p1: { ...project('p1'), name: 'alpha', path: '/w/alpha', lastActivityAt: NOW }, sc: scratchProject() } };
    expect(presentProjects(initialState(), store, NOW, '', false).sections[0]!.cards.map((c) => c.id)).toEqual(['p1']);
    expect(presentHome(initialState(), store, NOW).projects.map((c) => c.id)).toEqual(['p1']);
  });
  it('起動ダイアログの選択肢からも外す。並びは名前順のまま', () => {
    const store: Store = { ...storeWith(), projects: { ...storeWith().projects, sc: scratchProject() } };
    const state = { ...initialState(), overlay: { kind: 'newSession' as const, projectId: null, scratch: false } };
    const p = presentNewSession(state, store)!;
    expect(p.projects.map((x) => x.id)).toEqual(['alpha', 'beta']);
    expect(p.scratch).toBe(false);
    expect(presentNewSession({ ...state, overlay: { kind: 'newSession', projectId: null, scratch: true } }, store)!.scratch).toBe(true);
  });
});

describe('presentSession のフェーズ 3 の項目', () => {
  it('コンテキストとコストと要約の状態と昇格の可否', () => {
    const base = session('s1');
    const store: Store = {
      ...initialStore(),
      projects: { sc: scratchProject() },
      sessions: { s1: { ...base, projectId: 'sc', fromScratch: false, stats: { ...base.stats, contextPercent: 25, costUsd: 0.5 } } },
      artifacts: { a1: artDto('a1') },
      summaryPending: { s1: true as const },
    };
    const state = { ...initialState(), summaryFailed: { s1: 'LM Studio に繋がりません' } };
    const p = presentSession(state, store, NOW, 's1');
    expect(p.contextPercent).toBe(25);
    expect(p.cost).toBe('$0.50');
    expect(p.artifacts.map((a) => a.id)).toEqual(['a1']);
    expect(p.summaryPending).toBe(true);
    expect(p.summaryError).toBe('LM Studio に繋がりません');
    expect(p.canPromote).toBe(true);
    expect(p.fromScratch).toBe(false);
    expect(p.canSplit).toBe(false);
    expect(p.split).toBeNull();
  });
  it('分割はタブが 2 つ以上あるときだけ左右を返す', () => {
    const store = storeWith();
    store.runs = { r1: runDto('r1', 's1') };
    store.tabs = { t1: { ...tabDto('t1', 'r1', 'agent'), createdAt: 1 }, t2: { ...tabDto('t2', 'r1', 'shell'), createdAt: 2 } };
    const view = { ...defaultSessionView(), selectedTab: 't1', split: true, splitTab: 't9' };
    const state = { ...initialState(), sessionView: { s1: view } };
    const p = presentSession(state, store, NOW, 's1');
    expect(p.canSplit).toBe(true);
    // splitTab が閉じたタブを指していたら、左と違う最初のタブに落とす。
    expect(p.split).toEqual({ left: 't1', right: 't2' });
    const off = presentSession({ ...state, sessionView: { s1: { ...view, split: false } } }, store, NOW, 's1');
    expect(off.split).toBeNull();
    expect(off.canSplit).toBe(true);
  });
});

describe('presentSettings のフェーズ 3 の項目', () => {
  it('要約器と statusline と使用量の集計を渡す', () => {
    const store: Store = {
      ...initialStore(),
      settings: { workspaceRoot: '/w', claudeDir: '/c', tmuxPath: '/opt/homebrew/bin/tmux', terminalApp: 'terminal' as const, codePath: null, lmStudioUrl: 'http://127.0.0.1:1234', lmStudioModel: 'gemma', summaryFallback: false, summaryHourlyCap: 5, allowExternalSummarizer: false, syncClaudeConfig: false, nodePath: null, claudePath: null },
      statusline: { command: 'bash ~/.claude/statusline.sh', scriptPath: '/h/.claude/statusline.sh', installed: true },
      summarizerModels: ['gemma', 'qwen'],
      usageAggregate: { days: [{ day: '2026-09-18', inputTokens: 10, outputTokens: 2, sessions: 1 }], projects: [] },
    };
    const p = presentSettings(initialState(), store);
    expect(p).toMatchObject({ lmStudioUrl: 'http://127.0.0.1:1234', lmStudioModel: 'gemma', summaryFallback: false, summaryHourlyCap: 5, summarizerModels: ['gemma', 'qwen'], statuslineCommand: 'npm run hangar -- statusline install' });
    expect(p.statusline?.installed).toBe(true);
    expect(p.usageAggregate?.days).toHaveLength(1);
    expect(p.summarizerTest).toBeNull();
  });
});

describe('presentSessionRow のコストと run', () => {
  it('コストは通貨の記号と小数 2 桁。値が無ければ空文字で桁を崩さない', () => {
    const store = storeWith();
    expect(presentSessionRow(session('s1', { stats: { ...session('s1').stats, costUsd: 12.5 } }), store, NOW).cost).toBe('$12.50');
    expect(presentSessionRow(session('s1', { stats: { ...session('s1').stats, costUsd: 0.005 } }), store, NOW).cost).toBe('$0.01');
    expect(presentSessionRow(session('s1', { stats: { ...session('s1').stats, costUsd: 0 } }), store, NOW).cost).toBe('$0.00');
    expect(presentSessionRow(session('s1'), store, NOW).cost).toBe('');
  });
  it('runId は生きている run の id。run が無いか終わっていれば null', () => {
    const store = storeWith();
    expect(presentSessionRow(store.sessions.s1!, store, NOW).runId).toBeNull();
    store.runs = { r1: runDto('r1', 's1'), r0: runDto('r0', 's2', NOW) };
    expect(presentSessionRow(store.sessions.s1!, store, NOW).runId).toBe('r1');
    expect(presentSessionRow(store.sessions.s2!, store, NOW).runId).toBeNull();
  });
  it('行を組み立てる画面にもコストと run が乗る', () => {
    const store = storeWith();
    store.runs = { r1: runDto('r1', 's1') };
    store.sessions.s1 = { ...store.sessions.s1!, stats: { ...store.sessions.s1!.stats, costUsd: 3 } };
    expect(presentSessions(initialState(), store, NOW).rows[0]).toMatchObject({ id: 's1', cost: '$3.00', runId: 'r1' });
    expect(presentProject(initialState(), store, NOW, 'alpha').sessions[0]).toMatchObject({ id: 's1', cost: '$3.00', runId: 'r1' });
  });
});

describe('presentSession のフェーズ 3 の項目（値が無いとき）', () => {
  it('スクラッチでないプロジェクトは昇格できない。無い値はそのまま空にする', () => {
    const store = storeWith();
    store.sessions.s1 = { ...store.sessions.s1!, fromScratch: true };
    store.artifacts = { a1: artDto('a1'), a9: artDto('a9', { sessionIds: ['s9'] }) };
    const p = presentSession(initialState(), store, NOW, 's1');
    expect(p.canPromote).toBe(false);
    expect(p.fromScratch).toBe(true);
    expect(p.summaryPending).toBe(false);
    expect(p.summaryError).toBeNull();
    expect(p.contextPercent).toBeNull();
    expect(p.cost).toBe('');
    // 別のセッションのアーティファクトは出さない。
    expect(p.artifacts.map((a) => a.id)).toEqual(['a1']);
  });
  it('プロジェクトに属さないセッションは昇格できない', () => {
    const store = storeWith();
    expect(presentSession(initialState(), store, NOW, 's3').canPromote).toBe(false);
  });
});

describe('presentProject の右レール（端）', () => {
  it('スクラッチには印が付く。無いプロジェクトの右レールは空', () => {
    const store: Store = { ...initialStore(), projects: { sc: scratchProject() } };
    expect(presentProject(initialState(), store, NOW, 'sc').isScratch).toBe(true);
    expect(presentProject(initialState(), store, NOW, 'nope')).toMatchObject({ notFound: true, isScratch: false, todos: [], memo: null, artifacts: [] });
  });
});

describe('presentSettings の既定値', () => {
  it('設定がまだ届いていないときの要約器の既定と null の項目', () => {
    const p = presentSettings(initialState(), initialStore());
    expect(p).toMatchObject({ lmStudioUrl: '', lmStudioModel: null, summaryFallback: true, summaryHourlyCap: 20 });
    expect(p.statusline).toBeNull();
    expect(p.summarizerModels).toBeNull();
    expect(p.usageAggregate).toBeNull();
    expect(p.summarizerTest).toBeNull();
  });
  it('nodePath は無ければ空文字、あればそのまま', () => {
    expect(presentSettings(initialState(), initialStore()).nodePath).toBe('');
    const store: Store = { ...initialStore(), settings: fullSettings() };
    expect(presentSettings(initialState(), store).nodePath).toBe('');
    const withNode: Store = { ...initialStore(), settings: fullSettings({ nodePath: '/x/node' }) };
    expect(presentSettings(initialState(), withNode).nodePath).toBe('/x/node');
  });
});

const fullSettings = (over: Partial<SettingsDto> = {}): SettingsDto => ({ workspaceRoot: '/w', claudeDir: '/c', tmuxPath: null, terminalApp: 'terminal', codePath: null, lmStudioUrl: '', lmStudioModel: null, summaryFallback: true, summaryHourlyCap: 20, allowExternalSummarizer: false, syncClaudeConfig: false, nodePath: null, claudePath: null, ...over });
const syncStatus = (over: Partial<SyncStatusBody> = {}): SyncStatusBody => ({ state: 'idle', url: 'https://h', lastPushAt: NOW - 1000, lastPullAt: NOW - 60_000, pending: 0, error: null, deviceCount: 2, claudeConfig: { enabled: false, confirmed: false }, skipped: [], sweepPending: null, ...over });
const lockDto = (over: Partial<SessionLockDto> = {}): SessionLockDto => ({ deviceId: 'dev-b', deviceName: 'mini', runId: 'r1', heartbeatAt: NOW - 60_000, stale: false, ...over });

describe('同期の Presenter（フェーズ 4）', () => {
  it('ヘッダーの同期状態は種別ごとに文言が変わる', () => {
    const s = { ...initialState(), sync: { kind: 'idle' as const, lastAt: NOW - 60_000 }, pending: 2 };
    expect(presentShell(s, initialStore(), NOW).sync).toEqual({ visible: true, state: 'idle', label: '同期 1 分前', pending: 2, sweepPending: 0, skipped: 0, paused: false });
    expect(presentShell({ ...s, sync: { kind: 'off' } }, initialStore(), NOW).sync).toMatchObject({ visible: false, state: 'off', label: '' });
    expect(presentShell({ ...s, sync: { kind: 'pushing' } }, initialStore(), NOW).sync).toMatchObject({ visible: true, state: 'pushing', label: '送信中' });
    expect(presentShell({ ...s, sync: { kind: 'pulling' } }, initialStore(), NOW).sync).toMatchObject({ state: 'pulling', label: '受信中' });
    expect(presentShell({ ...s, sync: { kind: 'paused' } }, initialStore(), NOW).sync).toMatchObject({ state: 'paused', label: '一時停止中', paused: true });
    expect(presentShell({ ...s, sync: { kind: 'error', message: '切れました' } }, initialStore(), NOW).sync).toMatchObject({ state: 'error', label: '同期エラー: 切れました' });
    // まだ一度も往復していない間は、時刻の代わりに準備中と出す。
    expect(presentShell({ ...s, sync: { kind: 'idle', lastAt: null } }, initialStore(), NOW).sync).toMatchObject({ state: 'idle', label: '同期の準備中' });
  });
  it('ヘッダーに取り残しの件数と諦めた本文の件数が出る', () => {
    // 本文は 60 秒に 20 件ずつしか流れないので、残りが見えないと進んでいるか分からない。
    const state = { ...initialState(), sync: { kind: 'idle' as const, lastAt: NOW }, pending: 2 };
    const store: Store = { ...initialStore(), sync: syncStatus({ sweepPending: 1500, skipped: [{ key: 'k1', attempts: 3, message: 'x' }, { key: 'k2', attempts: 1, message: 'y' }] }) };
    expect(presentShell(state, store, NOW).sync).toMatchObject({ pending: 2, sweepPending: 1500, skipped: 2 });
    // 数えられない端末は 0 として渡す。ヘッダーは 0 件を描かないので、「分からない」と「無い」を分けなくてよい。
    expect(presentShell(state, { ...initialStore(), sync: syncStatus() }, NOW).sync).toMatchObject({ sweepPending: 0, skipped: 0 });
    expect(presentShell(state, initialStore(), NOW).sync).toMatchObject({ sweepPending: 0, skipped: 0 });
  });
  it('Settings のクラウドの節に取り残しと諦めた本文が出る', () => {
    // ヘッダーと違って、ここは 0 件も描く。0 と書いてあれば「追いついた」と読める。
    const store: Store = { ...initialStore(), sync: syncStatus({ sweepPending: 0, skipped: [{ key: 'k1', attempts: 3, message: '復号できません' }] }) };
    const p = presentSettings(initialState(), store, NOW).cloud;
    expect(p.sweepPending).toBe(0);
    expect(p.skipped).toEqual([{ key: 'k1', attempts: 3, message: '復号できません' }]);
    // 数えられない端末は null のまま渡し、画面が描かない。
    expect(presentSettings(initialState(), { ...initialStore(), sync: syncStatus() }, NOW).cloud.sweepPending).toBeNull();
    expect(presentSettings(initialState(), initialStore(), NOW).cloud).toMatchObject({ sweepPending: null, skipped: [] });
  });
  it('同期の行を足してもフェーズ 3 の使用量ゲージは残る', () => {
    const store = storeWith();
    store.usage = { fiveHour: { usedPercent: 40, resetsAt: null }, sevenDay: null, updatedAt: NOW - 60_000 };
    const p = presentShell({ ...initialState(), sync: { kind: 'idle', lastAt: NOW } }, store, NOW);
    expect(p.usage).toEqual({ fiveHour: 40, sevenDay: null, updatedLabel: '1 分前' });
    expect(p.sync.visible).toBe(true);
  });
  it('Settings のクラウドの節', () => {
    const store: Store = { ...initialStore(), sync: syncStatus({ pending: 3 }), devices: [{ id: 'd', name: 'mac', platform: 'darwin', lastSeenAt: NOW - 120_000, self: true, shell: null }], joinToken: 'tok', settings: fullSettings({ syncClaudeConfig: true }) };
    const p = presentSettings(initialState(), store, NOW).cloud;
    expect(p).toMatchObject({ configured: true, url: 'https://h', state: 'idle', paused: false, pending: 3, lastPullAt: '1 分前', joinToken: 'tok', syncClaudeConfig: true, configConfirmed: false });
    expect(p.devices).toEqual([{ id: 'd', name: 'mac', platform: 'darwin', lastSeen: '2 分前', self: true }]);
    const paused = presentSettings(initialState(), { ...store, sync: syncStatus({ state: 'paused', claudeConfig: { enabled: true, confirmed: true } }) }, NOW).cloud;
    expect(paused).toMatchObject({ configured: true, state: 'paused', paused: true, configConfirmed: true });
  });
  it('Settings の外のターミナルの節。自端末は測り直した値を使い、古い版の端末は分からないと書く', () => {
    const devices = [
      { id: 'd', name: 'mac', platform: 'darwin', lastSeenAt: NOW, self: true, shell: 'off' as const },
      { id: 'd2', name: 'mini', platform: 'darwin', lastSeenAt: NOW, self: false, shell: 'unsupported' as const },
      { id: 'd3', name: 'old', platform: 'darwin', lastSeenAt: NOW, self: false, shell: null },
    ];
    const store: Store = { ...initialStore(), devices, shellHook: { state: 'on', zshrc: '/Users/me/.zshrc', line: 'x', command: '/A/bin/hangar shell install' } };
    expect(presentSettings(initialState(), store, NOW).shell).toEqual({
      state: 'on', zshrc: '/Users/me/.zshrc', line: 'x', command: '/A/bin/hangar shell install', uninstallCommand: '/A/bin/hangar shell uninstall',
      devices: [{ id: 'd', name: 'mac', self: true, label: '入っています' }, { id: 'd2', name: 'mini', self: false, label: 'この Claude Code では使えません' }, { id: 'd3', name: 'old', self: false, label: '分かりません（hangar が古い版です）' }],
    });
    expect(presentSettings(initialState(), { ...store, shellHook: null }, NOW).shell.state).toBeNull();
  });
  it('同期を設定していない端末のクラウドの節', () => {
    const p = presentSettings(initialState(), initialStore(), NOW).cloud;
    expect(p).toMatchObject({ configured: false, url: null, state: 'off', paused: false, pending: 0, lastPullAt: '不明', joinToken: null, syncClaudeConfig: false, configConfirmed: false });
    expect(p.devices).toEqual([]);
    // off が届いているだけの端末も「設定していない」と同じ扱いにする。
    expect(presentSettings(initialState(), { ...initialStore(), sync: syncStatus({ state: 'off', url: null }) }, NOW).cloud.configured).toBe(false);
  });
  it('フェーズ 3 までの Settings の項目は消えていない', () => {
    const p = presentSettings(initialState(), { ...initialStore(), settings: fullSettings({ tmuxPath: '/t' }) }, NOW);
    expect(p).toMatchObject({ workspaceRoot: '/w', claudeDir: '/c', tmuxPath: '/t', terminalApp: 'terminal', mcpInstallCommand: 'npm run hangar -- mcp install', statuslineCommand: 'npm run hangar -- statusline install', summaryHourlyCap: 20 });
  });
  it('now を渡さない既存の呼び出しも通る', () => {
    expect(presentSettings(initialState(), initialStore()).cloud.state).toBe('off');
  });
});

describe('セッションのロック（フェーズ 4）', () => {
  it('他端末で実行中なら再開もフォークもこの PC で再開も止める', () => {
    const store: Store = { ...initialStore(), sessions: { s1: session('s1', { lock: lockDto(), remoteOnly: true }) } };
    const p = presentSession(initialState(), store, NOW, 's1');
    expect(p.lock).toEqual({ deviceName: 'mini', stale: false, heartbeat: '1 分前', label: 'mini で実行中' });
    expect(p.remoteOnly).toBe(true);
    expect(p.canResume).toBe(false);
    expect(p.canFork).toBe(false);
    expect(p.canResumeHere).toBe(false);
  });
  it('heartbeat が途絶えたロックは応答がありませんと見せ、この PC で再開だけを開ける（Ruling 14）', () => {
    const store: Store = { ...initialStore(), sessions: { s1: session('s1', { lock: lockDto({ heartbeatAt: NOW - 600_000, stale: true }) }) } };
    const p = presentSession(initialState(), store, NOW, 's1');
    expect(p.lock).toEqual({ deviceName: 'mini', stale: true, heartbeat: '10 分前', label: 'mini が応答がありません' });
    // 相手の run を止めには行かないので、同じ run の続きである再開とフォークは閉じたままにする。
    expect(p.canResume).toBe(false);
    expect(p.canFork).toBe(false);
    expect(p.canResumeHere).toBe(true);
  });
  it('stale のロックは、写しだけのセッションでもこの PC で再開ができる', () => {
    const store: Store = { ...initialStore(), sessions: { s1: session('s1', { lock: lockDto({ stale: true }), remoteOnly: true }) } };
    expect(presentSession(initialState(), store, NOW, 's1')).toMatchObject({ remoteOnly: true, canResume: false, canFork: false, canResumeHere: true });
  });
  it('生きているロックでは、写しの有無にかかわらずこの PC で再開を閉じる', () => {
    const local: Store = { ...initialStore(), sessions: { s1: session('s1', { lock: lockDto({ stale: false }) }) } };
    expect(presentSession(initialState(), local, NOW, 's1').canResumeHere).toBe(false);
    const remote: Store = { ...initialStore(), sessions: { s1: session('s1', { lock: lockDto({ stale: false }), remoteOnly: true }) } };
    expect(presentSession(initialState(), remote, NOW, 's1').canResumeHere).toBe(false);
  });
  it('写しだけで誰も動かしていなければ、この PC で再開ができる', () => {
    const store: Store = { ...initialStore(), sessions: { s1: session('s1', { lock: null, remoteOnly: true }) } };
    const p = presentSession(initialState(), store, NOW, 's1');
    expect(p.lock).toBeNull();
    expect(p.canResumeHere).toBe(true);
    expect(p.canResume).toBe(false);
    expect(p.canFork).toBe(false);
  });
  it('手元に本文があってロックが無ければ普通に再開できる', () => {
    const store: Store = { ...initialStore(), sessions: { s1: session('s1') } };
    expect(presentSession(initialState(), store, NOW, 's1')).toMatchObject({ lock: null, remoteOnly: false, canResume: true, canFork: true, canResumeHere: false });
  });
  it('hangar の run が無く外で動くセッションは、引き取りか attach の手を出す。作業中は出さない', () => {
    const live = (over = {}) => ({ sessionId: 'us1', status: 'idle' as const, name: null, nameSource: null, cwd: '/w/alpha', pid: 1, entrypoint: 'cli', ...over });
    const store: Store = { ...initialStore(), sessions: { s1: session('s1', { live: 'idle' }) }, live: [live()] };
    expect(presentSession(initialState(), store, NOW, 's1').outsideOpen).toBe('adopt');
    store.live = [live({ status: 'busy' })];
    expect(presentSession(initialState(), store, NOW, 's1').outsideOpen).toBeNull();
    // VS Code の拡張の中の claude は引き取らない。
    store.live = [live({ entrypoint: 'claude-vscode' })];
    expect(presentSession(initialState(), store, NOW, 's1').outsideOpen).toBeNull();
    store.live = [live({ status: 'busy', background: { jobId: 'abcd1234' } })];
    expect(presentSession(initialState(), store, NOW, 's1').outsideOpen).toBe('attach');
    store.runs = { r1: runDto('r1', 's1') };
    expect(presentSession(initialState(), store, NOW, 's1').outsideOpen).toBeNull();
  });
  it('本文が無いセッションと、そもそも無いセッションはロックの欄を空にする', () => {
    const store: Store = { ...initialStore(), sessions: { s1: session('s1', { hasTranscript: false }) } };
    expect(presentSession(initialState(), store, NOW, 's1')).toMatchObject({ lock: null, remoteOnly: false, canResume: false, canResumeHere: false });
    expect(presentSession(initialState(), store, NOW, 'zz')).toMatchObject({ notFound: true, lock: null, remoteOnly: false, canResumeHere: false });
  });
});
